---
name: Run Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "15 6 * * 0"  # Once weekly, on Sundays

jobs:
  perl-versions:
    name: "Retrieve available perl-tester versions"
    runs-on: ubuntu-latest

    outputs:
      perl-versions: ${{ steps.action.outputs.perl-versions }}

    steps:
      - id: action
        uses: perl-actions/perl-versions@v2
        with:
          since-perl: "5.08"

  test:
    name: "Linux, Perl v${{ matrix.perl-version }}"
    needs: perl-versions
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson (needs.perl-versions.outputs.perl-versions) }}

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    env:
      AUTHOR_TESTING: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Perl version
        run: perl -V

      - name: Install dependencies
        uses: perl-actions/install-with-cpanm@v1
        with:
          sudo: false
          args: "--installdeps ."

      - name: Build
        run: |
          perl Makefile.PL
          make

      - name: Test
        run: make test

      - name: Archive CPANM logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: build.log
          path: ~/.cpanm/work/*/build.log
